# Generated by Django 5.2.8 on 2025-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorials_title', models.CharField(max_length=200)),
                ('tutorials_published', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
