# Generated by Django 5.2.8 on 2025-11-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tutorials_delete_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriales_title', models.CharField(max_length=200)),
                ('tutoriales_content', models.TextField()),
                ('tutoriales_published', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
